### ISSUE TITLE
Add Temp Gauge for ground temp

### ISSUE THREAD

**Issue by Mohoganogan** [JoshuaCarroll/Raspberry-Pi-Weather-Station-Dashboard#17]
I added on my copy the following lines to add a gauge for the ground temp probe below all of the ambient temp lines.

var intGrnd = 0;

intGrnd = obj.GROUND_TEMPERATURE;

drawChart("chart_grnd", "Grnd_Temp", intGrnd, chartOptions());

I would suggest changing the temperature gauge to "Air-Temp" on the label on the web page

**Comment by JoshuaCarroll** [comment]
PLEASE.. submit your changes as a pull request!  I'd love to have someone else developing this thing!
