### ISSUE TITLE
Footer blocks data

### ISSUE THREAD

**Issue by Mohoganogan** [JoshuaCarroll/Raspberry-Pi-Weather-Station-Dashboard#19]
The footer blocks data on smaller screens.  I also is not tied to the bottom of the window so when you scroll it stays over the top of the data.
![screen shot 2016-07-08 at 6 42 23 am](https://cloud.githubusercontent.com/assets/20301455/16686350/2b3cf3f0-44d7-11e6-8e0d-af5436039b6b.png)

**Comment by JoshuaCarroll** [comment]
Please provide specifics to your environment.  What OS, browser, browser version, and screen resolution are you using?

**Comment by Mohoganogan** [comment]
MacOS 10.11.6
Both safari and chrome browsers
Display is 1200x800

Also on Iphone 6 in landscape mode
iOS 9.3.3

**Comment by JoshuaCarroll** [comment]
That's actually the same environment I'm using.  Can you check and make sure your browser(s) aren't using a cached copy of the CSS file?  Also, how does it look when you open the copy at http://n5jlc.duckdns.org/dev ?

**Comment by Mohoganogan** [comment]
Same results.  If the entire data set does not fit the the footer scrolls and continues to cover the data that ran behind it.

![screen shot 2016-07-09 at 8 00 57 pm](https://cloud.githubusercontent.com/assets/20301455/16711093/e9f91c4a-460f-11e6-8611-279872288394.png)

**Comment by Mohoganogan** [comment]
In the dashboard.css if you change position from absolute to fixed it stays.  However some how you will need to add some blank lines below the raw data to make it able to scroll above the footer.

**Comment by JoshuaCarroll** [comment]
Ok.  I have committed the change to the development branch.  You can see it live at http://raspberrypi/dev  

If this works for you I'll go ahead and merge it to master.

**Comment by Mohoganogan** [comment]
Yes that seems to do it.
