### ISSUE TITLE
Add compass for displaying wind direction

### ISSUE THREAD

**Issue by JoshuaCarroll** [JoshuaCarroll/Raspberry-Pi-Weather-Station-Dashboard#21]

**Comment by JoshuaCarroll** [comment]
Done

**Comment by isuroot** [comment]
The DropBox items for the compass/needle pngs are no longer valid.  Can they be updated?

**Comment by JoshuaCarroll** [comment]
LOL.  I never imagined anyone would be using this.  I'll see if I can find them.

**Comment by JoshuaCarroll** [comment]
Ok, I changed the reference in the Compass project (https://github.com/JoshuaCarroll/Compass-) so that they use graphics in the repo directly.  Try again and best of luck.

**Comment by isuroot** [comment]
Thanks!
