### ISSUE TITLE
WU Dew point calculation and upload

### ISSUE THREAD

**Issue by Mohoganogan** [JoshuaCarroll/Raspberry-Pi-Weather-Station-Dashboard#43]
Could you make the wunderground.php calculate dewpoint and upload it?
If you are interested in a simpler calculation that gives an approximation of dew point temperature if you know the observed temperature and relative humidity, the following formula was proposed in a 2005 article by Mark G. Lawrence in the Bulletin of the American Meteorological Society:
Td = T - ((100 - RH)/5.)
where Td is dew point temperature (in degrees Celsius), T is observed temperature (in degrees Celsius), and RH is relative humidity (in percent). Apparently this relationship is fairly accurate for relative humidity values above 50%.

**Comment by JoshuaCarroll** [comment]
Not sure this is running.  Need to add a debug mode to wunderground-api to be able to see the output.

**Comment by JoshuaCarroll** [comment]
This is working.  Will open another ticket for next cycle to have this data added to dashboard.
