### ISSUE TITLE
Adjust pressure/Calibrate pressure

### ISSUE THREAD

**Issue by Mohoganogan** [JoshuaCarroll/Raspberry-Pi-Weather-Station-Dashboard#44]
Be able to adjust pressure from absolute to mean sea level.  Possibly add a calibration factor based upon nearby official pressure source.

**Comment by JoshuaCarroll** [comment]
$air_value/(pow(1-($altitude/44330.0),5.255));

**Comment by JoshuaCarroll** [comment]
How can this still be open??  https://bugs.mysql.com/bug.php?id=44854

**Comment by JoshuaCarroll** [comment]
Done.
