### ISSUE TITLE
setup script should prompt for database userid, password, and database name

### ISSUE THREAD

**Issue by byrdman** [JoshuaCarroll/Raspberry-Pi-Weather-Station-Dashboard#49]
If hosting the dashboard on a "shared hosting" type environment it's quite likely that the user won't have access to the root database user.  Additionally, they will likely be forced to utilize a preassigned database name.

**Comment by JoshuaCarroll** [comment]
After prompting, this should write the values into the database.php file.  Also edit the README.md accordingly.

**Comment by byrdman** [comment]
I can't figure out how to assign this to me, but this pull request solves it: #55

**Comment by JoshuaCarroll** [comment]
@byrdman, why not just add the `CREATE DATABASE IF NOT EXISTS` command into the SETUP.sql?  Do you think we really need to ask?  If you agree, then I'll move it.

**Comment by byrdman** [comment]
Because I'd then have to create the entire SETUP.sql within the setup.sh script, this way I can just write out that small portion.

I could go either way on asking about creating the scheme.

**Comment by JoshuaCarroll** [comment]
No you wouldn't.  I would just add that line to the SETUP and let it run every time.  With the `IF NOT EXISTS` clause in there, it wouldn't hurt anything... right?  #SanityCheck

**Comment by byrdman** [comment]
The trouble is I'm not sure how to change the line within the setup.sql without either having the entire script within the setup.sh to write out to the file or perhaps having a "template" file that gets copied in.

Perhaps there is a way within a shell script to change a file instead of just writing out the whole thing but I'm not a shell script expert.

**Comment by JoshuaCarroll** [comment]
Done
